[workspace]
members = [
    "crates/rust-py-bindings",
    "crates/rust-core",
]
resolver = "2"

[workspace.dependencies]
rust-core = { path = "crates/rust-core" }


[profile.release]
opt-level = 3
lto = true
codegen-units = 1