name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install maturin and twine
      run: pip install maturin[patchelf] twine
      
    - name: Build wheel
      run: |
        cd crates/rust-py-bindings  
        maturin build --release
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd crates/rust-py-bindings
        ls -la target/wheels/
        twine upload target/wheels/*.whl