name: CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: x86_64
        args: --release --out dist --find-interpreter
        sccache: 'true'
        manylinux: auto
        working-directory: crates/rust-py-bindings
    - name: List built files
      run: |
        ls -la crates/rust-py-bindings/dist/
        ls -la dist/ || echo "No dist in root"
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux
        path: crates/rust-py-bindings/dist

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: x64
        args: --release --out dist --find-interpreter
        sccache: 'true'
        working-directory: crates/rust-py-bindings
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-windows
        path: crates/rust-py-bindings/dist

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: universal2-apple-darwin
        args: --release --out dist --find-interpreter
        sccache: 'true'
        working-directory: crates/rust-py-bindings
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-macos
        path: crates/rust-py-bindings/dist

  sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build sdist
      uses: PyO3/maturin-action@v1
      with:
        command: sdist
        args: --out dist
        working-directory: crates/rust-py-bindings
    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: wheels-sdist
        path: crates/rust-py-bindings/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux, windows, macos, sdist]
    steps:
    - uses: actions/download-artifact@v4
    - name: List downloaded files
      run: |
        find . -name "*.whl" -o -name "*.tar.gz"
        ls -la wheels-*/
    - name: Publish to PyPI
      uses: PyO3/maturin-action@v1
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      with:
        command: upload
        args: --non-interactive --skip-existing wheels-*/*