name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # 当推送v开头的tag时触发，如 v0.1.0
  workflow_dispatch:  # 允许手动触发

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install maturin
      run: pip install maturin[patchelf]
      
    - name: Build wheels
      run: |
        cd crates/rust-py-bindings
        maturin build --release --out ../../dist/ --find-interpreter
        
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist/

  publish:
    needs: build-wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: wheels
        path: dist/
        
    - name: Install twine
      run: pip install twine
      
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*