name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install dependencies
      run: pip install maturin[patchelf] pytest polars>=0.20.0
        
    - name: Build and install package
      run: |
        cd crates/rust-py-bindings
        maturin build --release
        pip install target/wheels/*.whl
        
    - name: Run Python tests
      run: |
        cd crates/rust-py-bindings
        python -m pytest tests/ -v
        
    - name: Run Rust tests
      run: |
        cd crates/rust-core
        cargo test