name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Create virtual environment and install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install maturin[patchelf] pytest polars>=0.20.0
        echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
        echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
        
    - name: Build and install package
      run: |
        cd crates/rust-py-bindings
        maturin develop --release
        
    - name: Run Python tests
      run: |
        cd crates/rust-py-bindings
        python -m pytest tests/ -v
        
    - name: Run Rust tests
      run: |
        cd crates/rust-core
        cargo test